name: Run Unit Tests for Task Analysis

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs tests on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code from the repository

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust Python version if necessary

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run unit tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run unit tests using pytest with options to stop at the first failure

      - name: Upload test results (if needed)
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: test-results
          path: test-results/  # Store test results in a directory if required

      - name: Notify on test result success or failure
        run: |
          if [[ $? -eq 0 ]]; then
            echo "Tests passed successfully!";
          else
            echo "Tests failed!";
            exit 1;  # Exit with error code if tests fail
          fi
